workflows:
  default-workflow:
    name: Build OMNI-ID Vault APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Extract ZIP contents
        script: |
          unzip -o omni_id_vault.zip
          cp -r omni_id_vault/* .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
